# Generated by Django 3.1.3 on 2020-11-22 06:25

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20201122_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=750)),
                ('location', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Null', 'NULL'), ('Planned', 'PLANNED'), ('Ongoing', 'ONGOING'), ('Completed', 'COMPLETED')], max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'example@example.com'", regex='^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$')])),
                ('contact', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 10 digits allowed.", regex='^\\d{10}$')])),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=755)),
            ],
            options={
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'example@example.com'", regex='^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$')])),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 10 digits allowed.", regex='^\\d{10}$')])),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(choices=[('Z', 'Zones'), ('M', 'Mechi'), ('K', 'Koshi'), ('S', 'Sagarmatha'), ('J', 'Janapkur'), ('N', 'Narayani'), ('B', 'Bagmati'), ('G', 'Gandaki'), ('L', 'Lumbini'), ('D', 'Dhaulagiri'), ('R', 'Ratpi'), ('B', 'Bheri'), ('K', 'Karnali'), ('S', 'Seti'), ('M', 'Mahakali')], default='Zone', max_length=100)),
                ('purpose', models.CharField(choices=[('P', 'Purpose'), ('f', 'Food'), ('e', 'Education'), ('c', 'Clothing'), ('h', 'Health'), ('s', 'Shelter')], default='Purpose', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='gallery')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.IntegerField()),
                ('volunteers', models.IntegerField()),
                ('rescued', models.IntegerField()),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'LGBTQ')], max_length=12, null=True)),
                ('email', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'example@example.com'", regex='^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$')])),
                ('contact', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 10 digits allowed.", regex='^\\d{10}$')])),
                ('time', models.CharField(max_length=75)),
                ('status', models.BooleanField(null=True)),
                ('joined_from', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='edited_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
