# Generated by Django 3.1.3 on 2020-11-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20201122_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='sponsor')),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=75)),
                ('detail', models.CharField(max_length=250)),
            ],
        ),
    ]
