# Generated by Django 3.1.3 on 2020-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='detail',
            field=models.CharField(max_length=750),
        ),
    ]
