# Generated by Django 3.1.3 on 2020-11-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20201122_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(null=True, upload_to='ID'),
        ),
    ]
