# Generated by Django 3.1.3 on 2020-11-22 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_volunteer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='job',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
    ]
