# Generated by Django 3.1.3 on 2020-11-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_auto_20201122_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='zone',
        ),
        migrations.AddField(
            model_name='donation',
            name='province',
            field=models.CharField(choices=[('P', 'Provinces'), ('P1', 'Province 1'), ('P2', 'Province 2'), ('P3', 'Province 3'), ('P4', 'Province 4'), ('P5', 'Province 5'), ('P6', 'Province 6'), ('P7', 'Province 7')], default='Province', max_length=100),
        ),
    ]
