# Generated by Django 3.1.3 on 2020-12-08 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_remove_blog_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'example@example.com'", regex='^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$')]),
        ),
    ]
