# Generated by Django 3.1.3 on 2020-12-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_auto_20201208_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='mode',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
