# Generated by Django 3.1.4 on 2020-12-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0013_donation_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='mode',
        ),
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=100),
        ),
    ]
