# Generated by Django 3.1.4 on 2020-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0017_auto_20201218_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='province',
            field=models.CharField(choices=[('P', 'Provinces'), ('P1', 'Province 1'), ('P2', 'Province 2'), ('P3', 'Province 3'), ('P4', 'Province 4'), ('P5', 'Province 5'), ('P6', 'Province 6'), ('P7', 'Province 7')], default='Province', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('P', 'Purpose'), ('f', 'Food'), ('e', 'Education'), ('c', 'Clothing'), ('h', 'Health'), ('s', 'Shelter')], default='Purpose', max_length=9),
        ),
    ]
