# Generated by Django 3.1.4 on 2020-12-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0018_auto_20201218_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='mode',
            field=models.CharField(choices=[('m', 'mode'), ('q', 'QR Code'), ('c', 'Cheque')], default='mode', max_length=9),
        ),
    ]
