# Generated by Django 3.1.4 on 2021-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0021_auto_20210307_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(null=True, upload_to='ID'),
        ),
    ]
