# Generated by Django 3.1.4 on 2021-09-22 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0024_donation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-z]$')]),
        ),
    ]
