# Generated by Django 3.1.4 on 2021-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0026_auto_20210922_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(null=True, upload_to='Voucher'),
        ),
    ]
