# Generated by Django 3.1.4 on 2021-09-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0027_donation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='image',
            new_name='profile',
        ),
    ]
