# Generated by Django 3.1.4 on 2021-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0029_auto_20210926_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
