# Generated by Django 3.1.4 on 2021-09-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0030_auto_20210930_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='sponsor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
