# Generated by Django 3.1.4 on 2021-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0031_donation_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Voucher'),
        ),
    ]
