# Generated by Django 3.1.4 on 2021-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0033_auto_20210930_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='mode',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='donation',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='donation',
            name='sponsor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
