# Generated by Django 3.1.4 on 2021-10-01 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0034_auto_20210930_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='sponsor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
