# Generated by Django 3.1.4 on 2021-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0035_auto_20211001_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='amount_spent',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
