# Generated by Django 3.1.4 on 2021-10-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0036_activities_amount_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='amount_spent',
            field=models.IntegerField(max_length=12),
        ),
    ]
