# Generated by Django 3.1.4 on 2021-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0037_auto_20211001_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='volunteer',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
