# Generated by Django 3.1.4 on 2021-10-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0039_auto_20211001_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='rescued',
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
