# Generated by Django 3.1.4 on 2021-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0040_auto_20211002_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='amount_spent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activities',
            name='volunteer',
            field=models.IntegerField(),
        ),
    ]
