# Generated by Django 3.1.3 on 2020-11-13 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0050_auto_20201006_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'example@example.com'", regex='^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$')])),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '98********'. Up to 10 digits allowed.", regex='^\\d{10}$')])),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact us'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
