# Generated by Django 3.1.3 on 2020-11-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0051_auto_20201113_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='position',
        ),
    ]
