# Generated by Django 3.1.3 on 2020-11-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0052_remove_volunteer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='time',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
