# Generated by Django 3.1.3 on 2020-11-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0056_auto_20201119_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=750)),
                ('location', models.CharField(max_length=250)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
    ]
