# Generated by Django 3.1.3 on 2020-11-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0057_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About',
        ),
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name_plural': 'Activitiees'},
        ),
    ]
