# Generated by Django 3.1.3 on 2020-11-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0058_auto_20201121_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('Planned', 'PLANNED'), ('Ongoing', 'ONGOING'), ('Completed', 'COMPLETED')], default='------', max_length=16),
        ),
    ]
