# Generated by Django 3.1.3 on 2020-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0060_auto_20201121_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('Null', 'NULL'), ('Planned', 'PLANNED'), ('Ongoing', 'ONGOING'), ('Completed', 'COMPLETED')], default='NULL', max_length=9),
        ),
    ]
